s/VehicleResponseObject/VehiclesResponse/g
s/VehiclePositionResponseObject/VehiclePositionsResponse/g
s/VehicleStatusResponseObject/VehicleStatusesResponse/g
s/TellTaleObject/TellTaleInfo/g
s/Object//g
