name: Release

permissions:
  contents: write

on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

env:
  GO_VERSION: "1.24.x"

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Go Semantic Release
        uses: go-semantic-release/action@v1
        with:
          allow-initial-development-versions: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest git tags
        run: git fetch --force --tags

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
